# Generated by Django 4.2.28 on 2026-02-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsnapshot',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='campaigns.campaign'),
        ),
        migrations.AlterUniqueTogether(
            name='metricsnapshot',
            unique_together={('campaign', 'date')},
        ),
    ]
